seed: 0
experiment_name: BiasedRPS
env_type: matrix_games
algo_name: maddpg
poilcy_type: qnet
sub_exp: ${env.scenario_name}/${algo_name}

env:
  scenario_name: biased_rps
  num_envs: null          
  max_steps: 100
  device: null            

model:
  shared_params: False
  centralized_critic: True
  depth: 2
  num_cells: 64

collector:
  frames_per_batch: 51200
  n_iters: 300
  total_frames: null      

buffer:
  memory_size: null      

train:
  num_epochs: 10
  minibatch_size: 4096
  lr: 1e-4
  max_grad_norm: 40.0
  device: null            

loss:
  gamma: 0.9
  tau: 0.005

eval:
  frequency: 10

hydra:
  run:
    dir: .  
  output_subdir: null